### ISSUE TITLE
Follow documentation

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#28]
This [wiki page](/kiwix/borg-backup/wiki/README) is a documentation of the tool as we want it for the initial release.

We want the tool to behave as described and that means tweaking a few things:

- [x] backup on a separate command #18
- [x] specify repo-name and periodicity as params #19
- [x] setup-new-repo should ask for borgbase key interactively #20
- [x] harmonize param names #21
- [x] use DSN to backup database instead of multiple fields #22
- [x] allow backing-up multiple databases #23
- [x] ~~allow backing-up multiple folders~~ (was documentation)
- [x] add a tool to restore/extract a backup #24
- [x] configure borgmatic periodicity #25
- [x] make sure borgmatic commands don't overlap #26
- [x] configure borgbase alertdays based on periodicity #27
